
name: Verify PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Build
        run: make build

      - name: Test
        run: make test

  verifyDeploy:
    needs: verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Install
        run: make OS_ARCH=linux_amd64 install

      - name: Set up terraform cli
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8

      - name: Download backlevel igc
        run: |
          curl -Lso /usr/local/bin/igc https://github.com/cloud-native-toolkit/ibm-garage-cloud-cli/releases/download/v1.39.2/igc-linux
          chmod +x /usr/local/bin/igc
          
          echo -n "igc path: "
          command -v igc
          echo ""
          echo "igc version:"
          igc --version

      - name: Apply terraform
        env:
          TF_LOG_PROVIDER: DEBUG
        run: |
          cd examples
          terraform init || exit 1
          terraform apply -auto-approve
          
          echo "***"
          echo "*** Validating terraform apply ***"
          echo "***"
          ../.github/scripts/validate-deploy.sh

      - name: Destroy terraform
        if: ${{ always() }}
        env:
          TF_VAR_git_host: github.com
          TF_VAR_git_org: cloud-native-toolkit-test
          TF_VAR_git_username: ${{ secrets.GIT_ADMIN_USERNAME }}
          TF_VAR_git_token: ${{ secrets.GIT_ADMIN_TOKEN }}
          TF_LOG_PROVIDER: DEBUG
        run: |
          cd examples
          terraform destroy -auto-approve

  verifyReleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

  verifyAll:
    needs: [verifyDeploy,verifyReleaser]
    runs-on: ubuntu-latest

    steps:
      - run: echo "Success"
